/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import datos.Habitacion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author estebansg
 */
public class HabitacionForm extends javax.swing.JFrame {
    public Habitacion habitacion;
    /**
     * Creates new form habitacionForm
     */
    public HabitacionForm() {
        habitacion = new Habitacion();
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnModificar.setVisible(false);
        this.btnEliminar.setVisible(false);
        this.txtId.setText(String.valueOf(Hotel.nuevoIdHabitacion()));
        this.txtId.setEnabled(false);
    }
    
    public HabitacionForm(int id) {
        habitacion = Hotel.buscarHabitacion(id);
        initComponents();
        setDatos();
        
        this.setLocationRelativeTo(null);
        txtId.setEnabled(false);
        this.txtId.setText(String.valueOf(id));
        this.btnRegistrar.setVisible(false);
    }
    
    public void setDatos(){
        this.txtId.setText(String.valueOf(habitacion.getId()));
        txtNumero.setText(String.valueOf(habitacion.getNumero()));
        cbxHabitaciones.setSelectedItem(String.valueOf(habitacion.getHabitaciones()));
        cbxBanios.setSelectedItem(String.valueOf(habitacion.getBanios()));
        if(habitacion.isAmueblada()){
            this.rbnAmuebSi.setSelected(true);
        } else {
            this.rbnAmuebNo.setSelected(true);
        }
        if(habitacion.isIntYcab()){
            this.rbnIntYCabSi.setSelected(true);
        } else {
            this.rbnIntYCabNo.setSelected(true);
        }
    }
    
    public boolean validarHab(int numero, int id){
        for(Habitacion hab : Hotel.listaHabitaciones){
            if(hab.getNumero()==numero){
                if(hab.getId()==id){
                    return true;
                }
                return false;
            }
        }
        return true;
    }
    
    void capturarDatos(){
        habitacion.setId(Integer.valueOf(txtId.getText()));
        habitacion.setNumero(Integer.valueOf(txtNumero.getText()));
        habitacion.setHabitaciones(Integer.valueOf(cbxHabitaciones.getSelectedItem().toString()));
        habitacion.setBanios(Integer.valueOf(cbxBanios.getSelectedItem().toString()));
        habitacion.setAmueblada(rbnAmuebSi.isSelected());
        habitacion.setIntYcab(rbnIntYCabSi.isSelected());
    }
    
    public boolean validaciones(){
        if(this.txtNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo no debe estar vacío.");
            return false;
        }
        if(!this.txtNumero.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Ingresa sólo números.");
            return false;
        }
        if(!this.validarHab(Integer.valueOf(txtNumero.getText()), Integer.valueOf(this.txtId.getText()))){
            JOptionPane.showMessageDialog(null, "El número de habitacion ya existe.");
            return false;
        }
        if(rbnAmuebSi.isSelected() == false && rbnAmuebNo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Se debe seleccionar una opción.");
            return false;
        }
        if(rbnIntYCabSi.isSelected() == false && rbnIntYCabNo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Se debe seleccionar una opción.");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAmueb = new javax.swing.ButtonGroup();
        groupIntYCab = new javax.swing.ButtonGroup();
        panelBase = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbnAmuebSi = new javax.swing.JRadioButton();
        rbnAmuebNo = new javax.swing.JRadioButton();
        rbnIntYCabSi = new javax.swing.JRadioButton();
        rbnIntYCabNo = new javax.swing.JRadioButton();
        txtNumero = new javax.swing.JTextField();
        cbxHabitaciones = new javax.swing.JComboBox<>();
        cbxBanios = new javax.swing.JComboBox<>();
        panelNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBase.setBackground(new java.awt.Color(249, 92, 73));
        panelBase.setMinimumSize(new java.awt.Dimension(600, 400));
        panelBase.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(249, 92, 73));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 20, 68, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Habitaciones:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 60, 105, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Baños:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 100, 54, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amueblada:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 140, 93, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Internet Y Cable:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 180, 134, 22);

        groupAmueb.add(rbnAmuebSi);
        rbnAmuebSi.setForeground(new java.awt.Color(255, 255, 255));
        rbnAmuebSi.setText("SÍ");
        rbnAmuebSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAmuebSiActionPerformed(evt);
            }
        });
        jPanel2.add(rbnAmuebSi);
        rbnAmuebSi.setBounds(170, 140, 40, 23);

        groupAmueb.add(rbnAmuebNo);
        rbnAmuebNo.setForeground(new java.awt.Color(255, 255, 255));
        rbnAmuebNo.setText("NO");
        rbnAmuebNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAmuebNoActionPerformed(evt);
            }
        });
        jPanel2.add(rbnAmuebNo);
        rbnAmuebNo.setBounds(220, 140, 40, 23);

        groupIntYCab.add(rbnIntYCabSi);
        rbnIntYCabSi.setForeground(new java.awt.Color(255, 255, 255));
        rbnIntYCabSi.setText("SÍ");
        rbnIntYCabSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnIntYCabSiActionPerformed(evt);
            }
        });
        jPanel2.add(rbnIntYCabSi);
        rbnIntYCabSi.setBounds(170, 180, 40, 23);

        groupIntYCab.add(rbnIntYCabNo);
        rbnIntYCabNo.setForeground(new java.awt.Color(255, 255, 255));
        rbnIntYCabNo.setText("NO");
        rbnIntYCabNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnIntYCabNoActionPerformed(evt);
            }
        });
        jPanel2.add(rbnIntYCabNo);
        rbnIntYCabNo.setBounds(220, 180, 40, 23);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumero);
        txtNumero.setBounds(170, 20, 100, 25);

        cbxHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel2.add(cbxHabitaciones);
        cbxHabitaciones.setBounds(170, 60, 60, 30);

        cbxBanios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel2.add(cbxBanios);
        cbxBanios.setBounds(170, 100, 60, 30);

        panelBase.add(jPanel2);
        jPanel2.setBounds(30, 60, 300, 220);

        panelNav.setBackground(new java.awt.Color(242, 189, 61));
        panelNav.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        panelNav.add(jLabel1);
        jLabel1.setBounds(430, 10, 25, 22);

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelNav.add(txtId);
        txtId.setBounds(460, 12, 70, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cama.png"))); // NOI18N
        panelNav.add(jLabel2);
        jLabel2.setBounds(30, 10, 40, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("HABITACIÓN");
        panelNav.add(jLabel9);
        jLabel9.setBounds(70, 10, 160, 29);

        panelBase.add(panelNav);
        panelNav.setBounds(0, 0, 550, 50);

        btnModificar.setBackground(new java.awt.Color(244, 201, 10));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelBase.add(btnModificar);
        btnModificar.setBounds(40, 290, 100, 35);

        btnRegresar.setBackground(new java.awt.Color(71, 71, 255));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelBase.add(btnRegresar);
        btnRegresar.setBounds(430, 290, 100, 35);

        btnRegistrar.setBackground(new java.awt.Color(78, 204, 0));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelBase.add(btnRegistrar);
        btnRegistrar.setBounds(150, 290, 100, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habitacion.jpg"))); // NOI18N
        panelBase.add(jLabel8);
        jLabel8.setBounds(340, 90, 190, 170);

        btnEliminar.setBackground(new java.awt.Color(204, 36, 36));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelBase.add(btnEliminar);
        btnEliminar.setBounds(150, 290, 100, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new HabitacionIndex(Hotel.listaHabitaciones).show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            if(!this.validaciones()){
                return;
            }
            
            capturarDatos();
            Hotel.listaHabitaciones.add(habitacion);
            Hotel.archivoHabitacion.Save(Hotel.listaHabitaciones);
            
            new HabitacionIndex(Hotel.listaHabitaciones).show();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(HabitacionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(!this.validaciones()){
                return;
            }
        
        this.capturarDatos();
        try {
            Hotel.archivoHabitacion.Save(Hotel.listaHabitaciones);
        } catch (IOException ex) {
            Logger.getLogger(HabitacionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        new HabitacionIndex(Hotel.listaHabitaciones).show();
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Hotel.listaHabitaciones.remove(habitacion);
        try {
            Hotel.archivoHabitacion.Save(Hotel.listaHabitaciones);
        } catch (IOException ex) {
            Logger.getLogger(HabitacionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        new HabitacionIndex(Hotel.listaHabitaciones).show();
        this.dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void rbnAmuebSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAmuebSiActionPerformed
        
    }//GEN-LAST:event_rbnAmuebSiActionPerformed

    private void rbnAmuebNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAmuebNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnAmuebNoActionPerformed

    private void rbnIntYCabSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnIntYCabSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnIntYCabSiActionPerformed

    private void rbnIntYCabNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnIntYCabNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnIntYCabNoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabitacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabitacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabitacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabitacionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxBanios;
    private javax.swing.JComboBox<String> cbxHabitaciones;
    private javax.swing.ButtonGroup groupAmueb;
    private javax.swing.ButtonGroup groupIntYCab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelNav;
    private javax.swing.JRadioButton rbnAmuebNo;
    private javax.swing.JRadioButton rbnAmuebSi;
    private javax.swing.JRadioButton rbnIntYCabNo;
    private javax.swing.JRadioButton rbnIntYCabSi;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
