/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import datos.Reservacion;
import datos.Usuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estebansg
 */
public class ReservacionIndex extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    SimpleDateFormat fechaF;
    /**
     * Creates new form index
     */
    public ReservacionIndex() {
        fechaF = new SimpleDateFormat("dd/MM/YYYY");
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnSalir.setVisible(false);
        modelo = (DefaultTableModel) this.tableIndex.getModel();
        this.cargarTabla();
    }
    
    public ReservacionIndex(boolean si) {
        fechaF = new SimpleDateFormat("dd/MM/YYYY");
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = (DefaultTableModel) this.tableIndex.getModel();
        this.btnMostrar.setVisible(false);
        this.btnRegresar.setVisible(false);
        this.btnNuevo.setVisible(false);
        this.misReservaciones();
        this.cargarTabla();
    }
    
    public void misReservaciones(){
        ArrayList<Reservacion> lista = new ArrayList();
        for(Reservacion reser : Hotel.listaReservaciones){
            if(Hotel.user.getId()==reser.getId_cliente()){
                lista.add(reser);
            }
        }
        Hotel.listaReservaciones = lista;
    }
    

    ReservacionIndex(ArrayList<Reservacion> listaReservaciones) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void buscar(int id){
        String array[] = new String[7];
        
        for(Reservacion reserv : Hotel.listaReservaciones){
            if(id==reserv.getId()){
                array[0] = String.valueOf(reserv.getId());
                array[1] = String.valueOf(reserv.getId_cliente());
                array[2] = String.valueOf(reserv.getId_habitacion());
                array[3] = fechaF.format(reserv.getFechaReservacion());
                array[4] = reserv.getHoraReservacion();
                array[5] = fechaF.format(reserv.getFechaEntrada());
                array[6] = fechaF.format(reserv.getFechaSalida());
                modelo.addRow(array);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "No se hayaron resultados");
    }
    
//    public void buscar(String nombre){
//        ArrayList<Usuario> lista = UsuarioController.index();
//        String array[] = new String[4];
//        boolean band=false;
//        
//        for(Usuario user : lista){
//            if(nombre.equals(user.getNombre())){
//                array[0] = String.valueOf(user.getId());
//                array[1] = user.getNombre();
//                array[2] = user.getCorreo();
//                array[3] = user.getTipo();
//                modelo.addRow(array);
//                band=true;
//            }
//        }
//        if(!band){
//            JOptionPane.showMessageDialog(null, "No se hayaron resultados");
//        }
//    }
    
    public void cargarTabla(){
        eliminar();
        String array[] = new String[7];
        
        for(Reservacion reserv : Hotel.listaReservaciones){
            array[0] = String.valueOf(reserv.getId());
            array[1] = String.valueOf(reserv.getId_cliente());
            array[2] = String.valueOf(reserv.getId_habitacion());
            array[3] = fechaF.format(reserv.getFechaReservacion());
            array[4] = reserv.getHoraReservacion();
            array[5] = fechaF.format(reserv.getFechaEntrada());
            array[6] = fechaF.format(reserv.getFechaSalida());
            modelo.addRow(array);
        }
    }
    
    public void eliminar(){
        int i=0;
        while(i<modelo.getRowCount()){
            modelo.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        lblUserIcon = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblCabecera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIndex = new javax.swing.JTable();
        textBuscar = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        panelBase.setBackground(new java.awt.Color(249, 92, 73));
        panelBase.setMaximumSize(new java.awt.Dimension(800, 600));
        panelBase.setMinimumSize(new java.awt.Dimension(800, 600));
        panelBase.setLayout(null);

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check (1).png"))); // NOI18N
        panelBase.add(lblUserIcon);
        lblUserIcon.setBounds(10, 0, 128, 100);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Reservaciones");
        panelBase.add(lblTitulo);
        lblTitulo.setBounds(340, 30, 152, 29);

        lblCabecera.setBackground(new java.awt.Color(242, 189, 61));
        lblCabecera.setOpaque(true);
        panelBase.add(lblCabecera);
        lblCabecera.setBounds(0, 0, 800, 100);

        tableIndex.setBackground(new java.awt.Color(192, 187, 60));
        tableIndex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableIndex.setForeground(new java.awt.Color(250, 250, 250));
        tableIndex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Cliente", "ID Habitación", "Fecha reservación", "Hora reservación", "Fecha entrada", "Fecha salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableIndex.setRowHeight(50);
        tableIndex.setSelectionBackground(new java.awt.Color(20, 215, 81));
        tableIndex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableIndexMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableIndex);
        if (tableIndex.getColumnModel().getColumnCount() > 0) {
            tableIndex.getColumnModel().getColumn(0).setMinWidth(80);
            tableIndex.getColumnModel().getColumn(0).setMaxWidth(80);
            tableIndex.getColumnModel().getColumn(3).setMinWidth(150);
            tableIndex.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        panelBase.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 760, 380);
        panelBase.add(textBuscar);
        textBuscar.setBounds(170, 500, 300, 30);

        btnMostrar.setBackground(new java.awt.Color(0, 121, 254));
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        panelBase.add(btnMostrar);
        btnMostrar.setBounds(590, 500, 90, 40);

        btnNuevo.setBackground(new java.awt.Color(0, 121, 254));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelBase.add(btnNuevo);
        btnNuevo.setBounds(690, 500, 90, 40);

        btnRefrescar.setBackground(new java.awt.Color(0, 121, 254));
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        panelBase.add(btnRefrescar);
        btnRefrescar.setBounds(20, 500, 90, 40);

        btnBuscar.setBackground(new java.awt.Color(0, 121, 254));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBase.add(btnBuscar);
        btnBuscar.setBounds(470, 500, 80, 30);

        btnRegresar.setBackground(new java.awt.Color(0, 121, 254));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(null);
        btnRegresar.setMargin(new java.awt.Insets(500, 500, 500, 500));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelBase.add(btnRegresar);
        btnRegresar.setBounds(690, 550, 90, 40);

        btnSalir.setBackground(new java.awt.Color(71, 71, 255));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelBase.add(btnSalir);
        btnSalir.setBounds(323, 553, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(tableIndex.getSelectedRow()==-1){
            return;
        }
        new ReservacionForm(Integer.valueOf(tableIndex.getValueAt(tableIndex.getSelectedRow(),0).toString())).show();
        this.dispose();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        new ReservacionForm().show();
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        eliminar();
        if(!this.textBuscar.getText().matches("[0-9]+")){
            if(!this.textBuscar.getText().matches("[a-z A-Z]+")){
                System.out.println("");
                cargarTabla();
                return;
            } 
//            else {
//                buscar(textBuscar.getText());
//            }
        } else {
            buscar(Integer.valueOf(textBuscar.getText()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new Menu().show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tableIndexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableIndexMouseClicked
        if(this.tableIndex.getSelectedColumn()==1){
            JOptionPane.showMessageDialog(null, Hotel.buscarUsuario(Integer.valueOf(tableIndex.getValueAt(tableIndex.getSelectedRow(),1).toString())));
        }
        if(this.tableIndex.getSelectedColumn()==2){
            JOptionPane.showMessageDialog(null, Hotel.buscarHabitacion(Integer.valueOf(tableIndex.getValueAt(tableIndex.getSelectedRow(),2).toString())));
        }
    }//GEN-LAST:event_tableIndexMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Hotel().show();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservacionIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservacionIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservacionIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservacionIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservacionIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JPanel panelBase;
    private javax.swing.JTable tableIndex;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables
}
